version: '3'

services:
  api:
    build:
      context: .
    container_name: sample-kt
    ports:
    - 8080:8080
    depends_on:
    - db
    environment:
      JAVA_ENV: dev
      DATABASE_URL: jdbc:postgresql://db:5432/exampledb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres

  db:
    image: postgres:latest
    container_name: bd-kt-db
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=exampledb
